version: "3"

services:
  with-docker-multi-env-production:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: with-docker-multi-env-production
    container_name: with-docker-multi-env-production
    ports:
      - "3003:3000"
    networks:
      - mylocalnetwork

networks:
  mylocalnetwork:
    external: true
