import * as React from "react"

import { Button } from "@/components/ui/button"
import {
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
} from "@/components/ui/card"
import Image from "next/image"
import Link from "next/link"
import { getSanityImageUrl } from "@/lib/sanityClient"
import { PostCard } from "@/types"
import { SanityImageSource } from "@sanity/image-url/lib/types/types"


export default function PostCard({ post }: { post: PostCard }) {
    return (
        <Card className="h-full w-full flex flex-col justify-between rounded-mycustomrounded">
            <CardHeader>
                <CardTitle className="py-2">{post?.title}</CardTitle>
                <CardDescription>
                    <span className="py-2 block">Generated By:</span>
                    <Image alt={`${post?.author?.name}`} src={getSanityImageUrl(post?.author?.image, 40)} width={50} height={50} className="rounded-full"
                        style={{ width: 'auto' }}
                        sizes="50px"
                    />
                    <span className="font-bold py-2 block" >{post?.author?.name}</span>
                </CardDescription>
            </CardHeader>
            <CardContent>
                <div>
                    <Link href={`/posts/${post?.slug?.current}`}>
                        <Image
                            width={250}
                            height={50}
                            alt={post?.title || "Post Image"}
                            src={getSanityImageUrl(post.mainImage, 250)}
                            style={{ width: 'auto' }}
                            className="rounded-mycustomrounded  my-2 object-cover"
                            sizes="250px"
                        />
                    </Link>
                </div>
            </CardContent>
            <CardFooter className="flex justify-between" >
                <Link href={`/posts/${post?.slug?.current}`} className="w-full">
                    <Button className="w-full">View</Button>
                </Link>
            </CardFooter>
        </Card>
    )
}
